name: dbt CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  dbt-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dbt
        run: pip install dbt-snowflake

      - name: Run dbt
        working-directory: webtpa_claims
        run: |
          dbt seed
          dbt run
          dbt test